spring:
  datasource:
    password: 1111
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.150.37.74:3306/weike?verifyServerCertificate=false&useSSL=true&useUnicode=true&characterEncoding=utf8
  mail:
      host: smtp.163.com
      username: yangquan95@163.com
      password: Bangnicayanlei59
      properties:
       mail:
        smtp:
         auth: true
         starttls:
          enable: true
          required: true
  http:
    multipart:
      enabled: true
      max-file-size: 10Mb
      resolve-lazily: true
      max-request-size: 10Mb





server:
  port: 8080

mybatis:
    type-aliases-package: weike.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
        cache-enabled: true
        use-column-label: true
        map-underscore-to-camel-case: true

event:
  service:
    pageCount: 8      #每页展示项目个数

jwt:
  header: Authorization
  secret: mySecret
  expiration: 606900
  tokenHead: "Bearer "

logging:
  file: weike.log

weike:
  images:
#    location: /home/tangxudong/images
    location: /home/yang/file




