spring:
  datasource:
    password: 1111
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/

server:
  port: 8080

mybatis:
    type-aliases-package: weike.entity
    mapper-locations: classpath:mapper/*.xml